name: Build and upload release

on: workflow_dispatch
#on:
#  release:
#    types:
#      - created

jobs:
  upload:
    strategy:
      matrix:
        os: [ ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    name: Upload ${{ matrix.os }} binaries to release ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.0
      - name: compile and upload
        shell: bash
        run: |
          dart pub get
          dart analyze
          export DART_BINS=$(ls src/*.dart)
          for dart_file in $DART_BINS; do
              echo "Compiling $dart_file"
              dart compile exe $dart_file
          done
          chmod +x src/*.exe
          export TARGET_GZ=${{ matrix.os }}_${{ github.event.release.tag_name }}.tar.gz
          tar -czvf $TARGET_GZ src/*.exe
          gh release upload ${{ github.event.release.tag_name }} $TARGET_GZ
    
