name: Build and upload release

#on: workflow_dispatch
on:
  release:
    types:
      - created

env:
  GH_TOKEN: ${{ github.token }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'ap-southeast-1'

jobs:
  buildAndUpload:
    permissions: write-all
    strategy:
      matrix:
        os: [ ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    name: Upload ${{ matrix.os }} binaries to release ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.0
      - name: Compile to exe
        shell: bash
        run: |
          dart pub get
          dart analyze
          export DART_BINS=$(ls src/*.dart)
          for dart_file in $DART_BINS; do
              echo "Compiling $dart_file"
              dart compile exe $dart_file
          done
      - name: Compress
        shell: bash
        run: |
          chmod +x src/*.exe
          export TARGET_GZ=${{ matrix.os }}_${{ github.event.release.tag_name }}.tar.gz
          tar -czvf $TARGET_GZ src/*.exe
      - name: Upload to S3
        run: |
          aws s3 sync ./src s3://squoosh-runner/release
    
